/*
	SPBASDEF.i
	Copyright (C) 2009 Paul C. Pratt

	You can redistribute this file and/or modify it under the terms
	of version 2 of the GNU General Public License as published by
	the Free Software Foundation.  You should have received a copy
	of the license along with this file; see the file COPYING.

	This file is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	license for more details.
*/

/*
	program SPecific BASic DEFinitions
*/


#define kStrAppName "Mini vMac"
#define kStrAppAbbrev "minivmac" /* [a-z0-9_]{1,8} */
#define MajorVersion 37
#define MinorVersion 03
#define kStrCopyrightYear "2020"
#define kMacCreatorSig "MnvM"
#define kBundleIdentifier "com.gryphel.minivmac"
#define kShortDescription "miniature Macintosh emulator"

#define kMaintainerName "Paul C. Pratt"
#define kStrHomePage "https://www.gryphel.com/"

#define Have_SPBLDOPT 1
#define Have_SPCNFGGL 1
#define Have_SPCNFGAP 1

/*
	Presentation is done with Metal through a CAMetalLayer. The
	fixed function OpenGL path that this replaced used glRasterPos2i
	and glDrawPixels, neither of which exists in an OpenGL core
	profile.
*/
#define UseMetalinOSX 1

#define HaveSwiftSrcFiles 1

/*
	Names of the two headers that carry the Swift/Objective-C
	boundary. The bridging header is checked in under src and
	exposes the C sources to Swift. The interface header is
	generated by the Swift compiler and is what the Objective-C
	sources import to see the Swift side.
*/
#define kSwiftBridgeHeaderName "CCOBRIDG.h"
#define kSwiftIfaceHeaderName "minivmac-Swift.h"
